"""add original filename to file versions

Revision ID: 49bcffd17bab
Revises: 0007d34b48f4
Create Date: 2026-06-26 20:46:49.604437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bcffd17bab'
down_revision: Union[str, Sequence[str], None] = '0007d34b48f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_versions",
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE file_versions
        SET original_filename = files.original_filename
        FROM files
        WHERE file_versions.file_id = files.id;
        """
    )

    op.alter_column(
        "file_versions",
        "original_filename",
        existing_type=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_versions', 'original_filename')
    # ### end Alembic commands ###
